name: Deploy DNYF Web to S3
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - 6-setup-github-actions-to-deploy-web-ui-automatically

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i -g @quasar/cli
      - run: quasar build
  upload:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p hello
      - run: echo hello > hello/world.txt
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: hello-world
          path: hello/world.txt
