name: Deploy DNYF Web to S3
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - 6-setup-github-actions-to-deploy-web-ui-automatically

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i -g @quasar/cli
      - run: npm install
      - run: quasar build
      - name: Upload Built App
        uses: actions/upload-artifact@v3
        with:
          name: dynf-frontend-app
          path: dist/
          retention-days: 3
  upload:
    needs: build
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dynf-frontend-app
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload S3
        uses: shallwefootball/s3-upload-action@master
        id: S3
        with:
          aws_key_id: ${{secrets.AWS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: dnyf-web-app
          source_dir: spa
      - name: Link To Report
        run: echo "https://s3.amazonaws.com/bucketName/${{steps.S3.outputs.object_key}}/index.html"
